# Generated by Django 4.1.6 on 2023-02-10 07:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsapp', '0002_category_newscategory_news_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subscribes',
            field=models.ManyToManyField(blank=True, related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
    ]
