# Generated by Django 4.1.6 on 2023-02-11 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_alter_category_subscribes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
        migrations.DeleteModel(
            name='NewsCategory',
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='news', to='newsapp.category'),
            preserve_default=False,
        ),
    ]
