# Generated by Django 4.1.6 on 2023-02-13 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0006_category_news_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='subscribes',
            new_name='subscribers',
        ),
    ]
